/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'id' : IDL.Nat,
  'difficulty' : IDL.Text,
  'text' : IDL.Text,
  'questionType' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'questions' : IDL.Vec(Question),
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([IDL.Text, IDL.Text], [Session], []),
  'deleteSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'difficulty' : IDL.Text,
    'text' : IDL.Text,
    'questionType' : IDL.Text,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([IDL.Text, IDL.Text], [Session], []),
    'deleteSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
    'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };